# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements. See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
# NOTE: For help with the syntax of this file, see:
# http://maven.apache.org/doxia/references/apt-format.html


env: 
  - secure: "lSMPBxR+ehMnZqirBXoJyN7IiFJuPDlvzKHPsdhgPrhuGjg//kSozSNvdCMPAMJb0P5fsX0DpeDBkWB/aGxHRoYWOEuusvHqylNMP2aNWxhVwrMuMfbvGQbSiOEOjw6UUEUHiMVctNSqPv34xwYARLeY20AZAS+bu+TIWpeBD7WJWsgGUjc7qKD2sb5UT9Da+8DDQDwgwr/NNbTn2z0VP4aJeCUTbGoGvbFrrrqyXzcmfNPtHwLGVzJ1wh5BrYUn0saU+RhrEjVMstRQImkKwgE0MxOCd4DzedoJWgHdK7BMAmAME6hTcZMGZ7jJ97EQeCNbGH0t/PaAV2yZ9lKbWmOEG5J0ZmfJUu/EoosISVUCobSll3xHiNRjuAGhFfeSvR3zHfRhdVwTedXuE+xU4jLoCG7xq6ai4kOhAQwUwyTgM0mcc7hjfyIPIwx7uzY2VHJ5+nJGQJe5WNKi74/4ZWMwIn4+JZV/iHbjy6dYrH91Ot61CxG+lwL+FLJdCV8UOA8Vz5oGfKMPYraKKnPByaHJRGfMB61fzuOosMrS67iXJZVjQvusxrtse06JrXR3HMhi3RWLJ02W70KCfqQ1C435D65THyz4072VgNGKsTqGaqIkoP7cgkmES2mWCU3u5eH5xhWHK0rJtl0sFcauFmE2IN+Px4GyuphX15y3MlA="
  - secure: "FCpMr2Q3BiJxjch+xGHrYCsE1M3YydtV43eIYp6OEuin7RXoa2k20RTR8AKdyMiVVGD926wz7CX03svJrDwhbMynS5pqt5HQ0CeMQOSJMf3/0nT+Al5t4eP2JpvjeSrxUxE+kUvNxkbLw0fghDDIpRoeBc8XcmebxcZPep3Km4b94vrarfOBReAHW8/4ToHQFQy6N4tNx3Z7jAjHeyGiKxr3NdjZvHcXxMsy5orKyP+Yle+6d7BHiXOGrCH7PEOZBW6VoH004/VovRBz9rJ2qznRjXnWu6Utp3l81ffxK/7A7YGL2kIX6phSmFV7cVS6Ps0tNBN6sfFYJjXQ5HDW4s08wOqbcWkkfATmNK6APNanvDocpXOgpNOy82q5c2xsCucWG7dOkZwyVlBDZjiVAs+zHfcFb9wXPTCEDDGs9bbrSqBV74wAE48rZQoF6y6BnKI/rRwNMvfbLhGmMkFh0FoWwOcma3IpjsHTEF5KAcqHRJ1AeFR4L58eB33yMXfK1c3LDvUX49QMORj+8nwADooP65t5Mt/AdYyo58pGDbYK363+ZhMmrzKyyN09Q3YxfWx6DEsBGHxHbSMVsgN/RkRlfiDHyh5Mun2QN+WUb27PJIbPh65AGlr+79wSr32DL4V/thqoiQZ14hm1gdE9zVFduhpbclSHAObmIfq6Zko="

language: java

jdk: oraclejdk8

install: true

cache:
  directories:
  - $HOME/.m2

script:
  - ./build-ci.sh